name: GitHub actions
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - c: clang
            cpp: clang++
          - c: gcc
            cpp: g++
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        cmake -B build .
        cmake --build build
        ctest --test-dir build

  coverage:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++  
    steps:
    - uses: actions/checkout@v1
    - name: Install lcov
      run: |
        sudo apt-get install -y lcov
    - name: Build and test
      run: |
        cmake -B build -DENABLE_COVERAGE=ON .
        cmake --build build
        ctest --test-dir build
    - name: Collect coverage and upload to codecov
      run: |
        lcov -c -d build -o cov.info
        bash <(curl -s https://codecov.io/bash) -f cov.info || echo "CodeCov did not collect repots"

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        cmake -B build .
        cmake --build build --config Release
        ctest --test-dir build -C Release